In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1,1,1], [5,5,5], [10,10,10]])


result = a + b
result1= a*b
result2= a-b

print("\nResult of broadcasting (a + b):")
print(result)
print("\nResult of broadcasting (a - b):")
print(result2)
print("\nResult of broadcasting (a * b):")
print(result1)



Result of broadcasting (a + b):
[[ 2  3  4]
 [ 6  7  8]
 [11 12 13]]

Result of broadcasting (a - b):
[[ 0  1  2]
 [-4 -3 -2]
 [-9 -8 -7]]

Result of broadcasting (a * b):
[[ 1  2  3]
 [ 5 10 15]
 [10 20 30]]
